sudo: required
services: docker
language: bash

install:
  - env | sort
  - docker pull postgres:9.6

script:
  - ./scripts/build.sh "keycloak-postgres-ssl:${TRAVIS_BRANCH}"
  - ./scripts/test.sh "keycloak-postgres-ssl:${TRAVIS_BRANCH}"

after_script:
  - docker images
